# Generated by Django 3.2.4 on 2023-11-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuhelper_app', '0003_alter_empty_classroom_classroom_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='empty_classroom',
            name='empty_day',
            field=models.CharField(default='1', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empty_classroom',
            name='empty_section',
            field=models.CharField(default='1', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empty_classroom',
            name='empty_week',
            field=models.CharField(default='1', max_length=20, null=True),
        ),
    ]
