# Generated by Django 3.2.4 on 2023-11-05 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuhelper_app', '0005_empty_classroom_campus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empty_classroom',
            old_name='empty_section',
            new_name='empty_session',
        ),
    ]
