# Generated by Django 3.2.4 on 2023-11-06 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuhelper_app', '0006_rename_empty_section_empty_classroom_empty_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empty_classroom',
            name='floor_id',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
