# Generated by Django 3.2.4 on 2023-11-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuhelper_app', '0008_auto_20231106_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empty_classroom',
            name='empty_session',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
