# Generated by Django 3.2.4 on 2023-11-07 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuhelper_app', '0010_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='trade_post',
            fields=[
                ('ID', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, null=True)),
                ('content', models.CharField(max_length=1024, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuhelper_app.customuser')),
            ],
        ),
        migrations.DeleteModel(
            name='temp',
        ),
    ]
