# Generated by Django 3.2.4 on 2023-11-07 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuhelper_app', '0011_auto_20231107_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade_post',
            old_name='ID',
            new_name='id',
        ),
    ]
