# Generated by Django 3.2.4 on 2023-11-07 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuhelper_app', '0013_auto_20231107_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user',
            new_name='admin',
        ),
    ]
