# Generated by Django 3.2.4 on 2023-11-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuhelper_app', '0014_rename_user_customuser_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_share',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
