# Generated by Django 3.2.4 on 2023-11-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuhelper_app', '0016_auto_20231107_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatars',
            field=models.ImageField(default='avatars/lazy_cat.jpg', upload_to='avatars'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='qq',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
