# Generated by Django 3.2.4 on 2023-11-08 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuhelper_app', '0019_auto_20231108_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='post_type',
        ),
        migrations.RemoveField(
            model_name='file_share',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='file_share',
            name='author',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='stuhelper_app.customuser'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='stuhelper_app.customuser'),
        ),
    ]
