# Generated by Django 3.2.4 on 2023-11-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuhelper_app', '0020_auto_20231108_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_share',
            name='hash_id',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='hash_id',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='file_share',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
