# Generated by Django 3.2.4 on 2023-11-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuhelper_app', '0022_customuser_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
