# Generated by Django 3.2.4 on 2023-11-09 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuhelper_app', '0028_newuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newUser',
        ),
    ]
