# Generated by Django 3.2.4 on 2023-11-10 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuhelper_app', '0030_post_brief_content'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='post',
        #     name='brief_content',
        # ),
    ]
