# Generated by Django 3.2.4 on 2023-11-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuhelper_app', '0031_remove_post_brief_content'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='post',
        #     name='brief_content',
        #     field=models.CharField(default='This is breif content', max_length=15),
        # ),
    ]
