# Generated by Django 3.2.4 on 2023-11-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuhelper_app', '0034_alter_post_brief_content'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='post',
        #     name='brief_content',
        #     field=models.CharField(max_length=25, null=True),
        # ),
    ]
