# Generated by Django 3.2.4 on 2023-11-10 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuhelper_app', '0035_alter_post_brief_content'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='post',
        #     old_name='brief_content',
        #     new_name='brief',
        # ),
    ]
