# Generated by Django 3.2.4 on 2023-11-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuhelper_app', '0037_auto_20231110_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='brief_content',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
