# Generated by Django 3.2.4 on 2023-11-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuhelper_app', '0038_post_brief_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='motto',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
