# Generated by Django 3.2.4 on 2023-11-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuhelper_app', '0039_customuser_motto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='motto',
            field=models.CharField(default='这个人很懒，什么都没有留下', max_length=50, null=True),
        ),
    ]
