# Generated by Django 3.2.4 on 2023-11-10 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuhelper_app', '0040_alter_customuser_motto'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Star_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuhelper_app.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuhelper_app.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='User_Like_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuhelper_app.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuhelper_app.customuser')),
            ],
        ),
    ]
