# Generated by Django 3.2.4 on 2023-11-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuhelper_app', '0041_user_like_post_user_star_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_like_post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_star_post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
