# Generated by Django 3.2.4 on 2023-11-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuhelper_app', '0042_auto_20231110_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='temp_like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='temp_star',
            field=models.BooleanField(default=False),
        ),
    ]
