# Generated by Django 3.2.4 on 2023-11-12 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuhelper_app', '0044_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_token', models.CharField(max_length=16, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuhelper_app.customuser')),
            ],
        ),
    ]
