# Generated by Django 3.2.4 on 2023-11-12 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuhelper_app', '0045_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='start_time',
            new_name='expire_date',
        ),
    ]
