# Generated by Django 3.2.4 on 2023-11-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuhelper_app', '0047_alter_session_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
