# Generated by Django 3.2.4 on 2023-11-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuhelper_app', '0049_alter_session_session_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='protected',
            field=models.BooleanField(default=False),
        ),
    ]
