# Generated by Django 3.2.4 on 2023-11-15 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuhelper_app', '0052_auto_20231115_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stuhelper_app.post'),
        ),
    ]
