# Generated by Django 3.2.4 on 2023-11-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuhelper_app', '0053_alter_message_post'),
    ]

    operations = [

    ]
