# Generated by Django 3.2.4 on 2023-11-16 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuhelper_app', '0054_customuser_anonymous_img'),
    ]

    operations = [

    ]
