# Generated by Django 3.2.4 on 2023-11-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuhelper_app', '0055_remove_customuser_anonymous_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='anonymous_img',
            field=models.CharField(default='avatars/anonymous.jpg', max_length=50),
        ),
    ]
