# Generated by Django 3.2.4 on 2023-12-20 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuhelper_app', '0056_customuser_anonymous_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Private_Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=256, null=True)),
                ('read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_receive_this', to='stuhelper_app.customuser')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_send_this', to='stuhelper_app.customuser')),
            ],
        ),
    ]
