# Generated by Django 3.2.4 on 2023-12-26 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuhelper_app', '0058_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=256, null=True)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuhelper_app.customuser')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuhelper_app.post')),
            ],
        ),
    ]
