# Generated by Django 3.2.4 on 2023-12-26 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuhelper_app', '0059_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='protected',
        ),
    ]
