# Generated by Django 3.2.4 on 2023-12-26 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuhelper_app', '0060_remove_session_protected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stuhelper_app.customuser'),
        ),
    ]
